require 'config.options'
require 'config.keymaps'
require 'config.autocmds'
require 'config.lsp'

-- core plugins
require 'plugins.everforest'
require 'plugins.mini'
require 'plugins.treesitter'
require 'plugins.oil'
require 'plugins.heirline'
require 'plugins.snacks'
require 'plugins.completion'
require 'plugins.meow'
require 'plugins.markdown'
require 'plugins.autopairs'
require 'plugins.conform'
require 'plugins.todo-comments'
require 'plugins.which-key'
